from . import backends
from . import hetero
from . import jraph
from . import tree
from .backends import get_backend
from .optional import module_if_loaded

# Import einops functions, which work the same way as anytensor.
from einops import einsum, pack, unpack, rearrange, reduce

from .segment import (
    segment_sum,
    segment_max,
    segment_min,
    segment_mean,
    segment_count,
    segment_variance,
    segment_normalize,
    segment_softmax,
    segment_min_or_constant,
    segment_max_or_constant,
    partition_softmax,
    partition_ids,
    partition_cache,
    enable_torchscript,
)

from .core import (
    repeat,
    take,
    exp,
    log,
    sum,
    min,
    max,
    mean,
    prod,
    shape,
    cumsum,
    reshape,
    transpose,
    concatenate,
    split,
    stack,
    maximum,
    minimum,
    sqrt,
    rsqrt,
    where,
    clip,
    astype,
    cast,
    zeros_like,
    ones_like,
    full_like,
    zeros,
    ones,
    full,
    arange,
    matmul,
    inf,
    ninf,
    nan,
    pi,
    e,
    newaxis,
    finfo,
    iinfo,
    dtype,
    is_nan,
    is_finite,
    is_inf,
    isnan,
    isfinite,
    isinf,
    fill_nan,
    nan_fill,
    fill_nan_mask,
    nan_fill_mask,
    nan_to_num,
    equal_nan,
    promote,
    promote_scalars,
    promote_options,
    align_arrays,
)

from .semantics import empty_segment_identity
from .typing import (
    ArrayT,
    Axes,
    Bool,
    DtypeLike,
    Float,
    FloatArray,
    Inexact,
    Int,
    IntArray,
    Integer,
    Num,
    Real,
    SegmentIds,
    SegmentOut,
    SegmentValues,
    ShapeLike,
    ShapeSize,
    Shaped,
    ShapedArray,
    enable_typecheck,
)

try:
    from ._version import __version__
except ImportError:  # pragma: no cover
    __version__ = "0.0.0"

__all__ = [
    "backends",
    "hetero",
    "jraph",
    "tree",
    "get_backend",
    "module_if_loaded",
    "ArrayT",
    "Axes",
    "Bool",
    "DtypeLike",
    "Float",
    "FloatArray",
    "Inexact",
    "Int",
    "IntArray",
    "Integer",
    "Num",
    "Real",
    "SegmentIds",
    "SegmentOut",
    "SegmentValues",
    "ShapeLike",
    "ShapeSize",
    "Shaped",
    "ShapedArray",
    "enable_typecheck",
    "einsum",
    "pack",
    "unpack",
    "rearrange",
    "reduce",
    "segment_sum",
    "segment_max",
    "segment_min",
    "segment_mean",
    "segment_count",
    "segment_variance",
    "segment_normalize",
    "segment_softmax",
    "segment_min_or_constant",
    "segment_max_or_constant",
    "partition_softmax",
    "partition_ids",
    "partition_cache",
    "enable_torchscript",
    "repeat",
    "take",
    "exp",
    "log",
    "sum",
    "min",
    "max",
    "mean",
    "prod",
    "shape",
    "cumsum",
    "reshape",
    "transpose",
    "concatenate",
    "split",
    "stack",
    "maximum",
    "minimum",
    "sqrt",
    "rsqrt",
    "where",
    "clip",
    "astype",
    "cast",
    "zeros_like",
    "ones_like",
    "full_like",
    "zeros",
    "ones",
    "full",
    "arange",
    "matmul",
    "inf",
    "ninf",
    "nan",
    "pi",
    "e",
    "newaxis",
    "finfo",
    "iinfo",
    "dtype",
    "is_nan",
    "is_finite",
    "is_inf",
    "isnan",
    "isfinite",
    "isinf",
    "fill_nan",
    "nan_fill",
    "fill_nan_mask",
    "nan_fill_mask",
    "nan_to_num",
    "equal_nan",
    "promote",
    "promote_scalars",
    "promote_options",
    "align_arrays",
    "empty_segment_identity",
    "__version__",
]
