from . import backends
from .backends import get_backend

# Import einops functions, which work the same way as anytensor.
from einops import einsum, pack, unpack, rearrange, reduce

from .segment import (
    segment_sum,
    segment_max,
    segment_min,
    segment_mean,
    segment_count,
    segment_variance,
    segment_normalize,
    segment_softmax,
    segment_min_or_constant,
    segment_max_or_constant,
    partition_softmax,
)

from .core import (
    repeat,
    take,
    exp,
    log,
    sum,
    min,
    max,
    mean,
    prod,
    shape,
    cumsum,
    reshape,
    transpose,
    concatenate,
    stack,
    maximum,
    minimum,
    sqrt,
    rsqrt,
    where,
    clip,
    astype,
    cast,
    zeros_like,
    ones_like,
    full_like,
    zeros,
    ones,
    full,
    arange,
    matmul,
    is_nan,
    is_finite,
    is_inf,
    isnan,
    isfinite,
    isinf,
    fill_nan,
    nan_fill,
    nan_to_num,
    equal_nan,
    promote,
    promote_scalars,
    promote_options,
    align_arrays,
)

from .semantics import empty_segment_identity

try:
    from ._version import __version__
except ImportError:  # pragma: no cover
    __version__ = "0.0.0"

__all__ = [
    "backends",
    "get_backend",
    "einsum",
    "pack",
    "unpack",
    "rearrange",
    "reduce",
    "segment_sum",
    "segment_max",
    "segment_min",
    "segment_mean",
    "segment_count",
    "segment_variance",
    "segment_normalize",
    "segment_softmax",
    "segment_min_or_constant",
    "segment_max_or_constant",
    "partition_softmax",
    "repeat",
    "take",
    "exp",
    "log",
    "sum",
    "min",
    "max",
    "mean",
    "prod",
    "shape",
    "cumsum",
    "reshape",
    "transpose",
    "concatenate",
    "stack",
    "maximum",
    "minimum",
    "sqrt",
    "rsqrt",
    "where",
    "clip",
    "astype",
    "cast",
    "zeros_like",
    "ones_like",
    "full_like",
    "zeros",
    "ones",
    "full",
    "arange",
    "matmul",
    "is_nan",
    "is_finite",
    "is_inf",
    "isnan",
    "isfinite",
    "isinf",
    "fill_nan",
    "nan_fill",
    "nan_to_num",
    "equal_nan",
    "promote",
    "promote_scalars",
    "promote_options",
    "align_arrays",
    "empty_segment_identity",
    "__version__",
]
